### ISSUE TITLE
How to contribute 

### ISSUE THREAD

**Issue by mercs600** [dimanech/atlas-guide#39]
Hi guys, this is really nice tool. I was looking for something like this ;-) I have some questions. 
1) What is the problem with supporting styleguide variables as list ? 
2) Why styleguide variables should be placed in one file ? 
3) I would like to fork it and make some changes for my project structure. How do you work with sources ? When I make some changes in your sources I have to run app/atlas-guide.build() each time ? How do you debug it ? Could you provide me some tips ?

**Comment by dimanech** [comment]
Hi there, thanks!

1. As I understood you correct, we decided to use plane variables instead of variables maps for several reasons: 1) compatibility with CSS custom properties 2) development experience (autocomplition even on simple editors, no additional wrappers, linting).

2. We do not faced with cases when we need several files for project variables. I do not sure, but probably sass imports could work for this case. For details, please see `models/projectconstants.js`. Work with project variables is tricky part because you need to really mimic project structure and compile sass under the hood.

3. For atlas development you could use `dev:atlas` gulp task that start local server with hot reload. Styleguide example will be compiled to `./atlas` directory.

    Templates are cached so you need to restart gulp task after templates updates.

    Project has linting and editor config file. Please run `npm run copyhooks` once to install git hooks right after project is cloned.

     Also take a look on tests.

Hope it helps. Thanks!

**Comment by mercs600** [comment]
@dimanech thanks for answers. According to development. I was thinking about the code responsible for build process - app/atlas-guide.js. I just set the node debugging in VSC. 

Have you thought about possibility to external your app by some external plugins ?

**Comment by dimanech** [comment]
Good call, I never thought about plugins system and extensibility in that way. @mercs600 Do you have some examples about possible plugins that could be added?

**Comment by dimanech** [comment]
@mercs600 I will close this issue. Please fill free to reopen it in case of any.
